print("Hello World!")
print("Hej igen")
print("Det er fedt nok at printe!")
print("Vi laver lige et print mere.")
print('Sådan kan vi også printe.')
print("Go’ stil med 'enkelt anførelsestegn'")
print('Vi kan også printe “gåseøjne” sådan her')
print("""Vi kan også printe""" """gåseøjne sådan her""")
